name: dev-push

on:
    push:
        branches: [dev]

jobs:
    test-build:
        uses: /.github/workflows/test-build.yml
    deploy:
        uses: /.github/workflows/deploy.yml
        with:
            lambdaFunctionName: terragridsProjectContractApiDev
