name: master-push

on:
    push:
        branches: [master]

jobs:
    test-build:
        uses: /.github/workflows/test-build.yml
    deploy:
        uses: /.github/workflows/deploy.yml
        with:
            lambdaFunctionName: terragridsProjectContractApiDev
