name: test-build

on:
    workflow_call:

jobs:
    test:
        name: Test ${{ github.ref_name }} on node ${{ matrix.node_version }} and ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node_version: ['16']
                os: [ubuntu-latest]
                reach_hash: [4ca32459]

        steps:
            - name: Setup node.js environment
              uses: actions/setup-node@v3
              with:
                  # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0
                  node-version: ${{ matrix.node_version }}

            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Build and test Reach backend (version ${{ matrix.reach_hash }})
              run: |
                  cd reach
                  REACH_VERSION=${{ matrix.reach_hash }} ./reach run project-contract
                  cd ..
              env:
                  REACH_CONNECTOR_MODE: ALGO

            - name: Install npm modules and run tests
              run: |
                  npm install
                  npm test
                  npm run lint
              env:
                  ENV: dev
                  AWS_REGION: local
